### ISSUE TITLE
测评训练的权重文件，显示与网络格式不服

### ISSUE THREAD

**Issue by EvelynCarter** [EdwardPooh/douzero-resnet-2.0#13]
douzero\evaluation\deep_agent.py", line 41, in __init__
    self.model = _load_model(position, model_path, self.model_type)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\BaiduSyncdisk\DouZero_II\Resnet_2.0_lock\douzero\evaluation\deep_agent.py", line 26, in _load_model
    model.load_state_dict(model_state_dict)
  File "D:\anaconda3\envs\DouZero_JJ\Lib\site-packages\torch\nn\modules\module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GeneralModelTransformer:
        size mismatch for layer1.0.conv1.weight: copying a param with shape torch.Size([72, 72, 3]) from checkpoint, the shape in current model is torch.Size([12, 12, 3]).
        size mismatch for layer1.0.bn1.weight: copying a param with shape torch.Size([72]) from checkpoint, the shape in current model is torch.Size([12]).
        size mismatch for layer1.0.bn1.bias: copying a param with shape torch.Size([72]) from checkpoint, the shape in current model is torch.Size([12]).
        size mismatch for layer1.0.bn1.running_mean: copying a param with shape torch.Size([72]) from checkpoint, the shape in current model is torch.Size([12]).
        size mismatch for layer1.0.bn1.running_var: copying a param with shape torch.Size([72]) from checkpoint, the shape in current model is torch.Size([12]).
        size mismatch for layer1.0.conv2.weight: copying a param with shape torch.Size([72, 72, 3]) from checkpoint, the shape in current model is torch.Size([12, 12, 3]).
        size mismatch for layer1.0.bn2.weight: copying a param with shape torch.Size([72]) from checkpoint, the shape in current model is torch.Size([12]).
        size mismatch for layer1.0.bn2.bias: copying a param with shape torch.Size([72]) from checkpoint, the shape in current model is torch.Size([12]).

**Comment by EdwardPooh** [comment]
already update
