### ISSUE TITLE
最新的版本中去掉了check_no_bombs 对后续训练影响大吗

### ISSUE THREAD

**Issue by EvelynCarter** [EdwardPooh/douzero-resnet-2.0#14]
def check_no_bombs(self, a):
        reshaped_a = a[:52].view(-1, 4)
        sums = reshaped_a.sum(dim=1)
        if torch.all(sums < 4) and a[52] + a[53] < 2:
            return True
        else:
            return False
            
 if self.check_no_bombs(z[0, 2]) and self.check_no_bombs(z[0, 3]) and (0 in z[0, 11]):
            out = _win_rate
        else:
            out = _win_rate * win + (1. - _win_rate) * lose

**Comment by EvelynCarter** [comment]
@EdwardPooh

**Comment by EdwardPooh** [comment]
影响很小

**Comment by EvelynCarter** [comment]
> 影响很小
@EdwardPooh 
训练到32亿左右 突然不会打牌了。是学了效率过大导致的吗
