### ISSUE TITLE
Running on the GPU will always freeze

### ISSUE THREAD

**Issue by markc-614** [EdwardPooh/douzero-resnet-2.0#15]
docker image: nvcr.io/nvidia/pytorch:24.08-py3
gpu: NVIDIA A100-SXM4-40GB
torch version: 2.5
cuda version: 12.06

```
git clone https://github.com/EdwardPooh/douzero-resnet-2.0.git
pip install -r requirements.txt
```
run cmd
```
python train.py --total_frames=6000
```
outputs
```
Creating log directory: douzero_checkpoints/douzero_II
Saving arguments to douzero_checkpoints/douzero_II/meta.json
Saving messages to douzero_checkpoints/douzero_II/out.log
Saving logs data to douzero_checkpoints/douzero_II/logs.csv
Saving logs' fields to douzero_checkpoints/douzero_II/fields.csv
[INFO:3006 utils:68 2024-09-25 01:46:45,403] Device 0 Actor 0 started.
[INFO:3083 utils:68 2024-09-25 01:46:47,082] Device 0 Actor 1 started.
[INFO:3161 utils:68 2024-09-25 01:46:48,752] Device 0 Actor 2 started.
[INFO:3377 utils:68 2024-09-25 01:46:50,467] Device 0 Actor 3 started.
[INFO:2890 dmc:219 2024-09-25 01:46:55,461] Saving checkpoint to douzero_checkpoints/douzero_II/model.tar
[INFO:2890 dmc:259 2024-09-25 01:46:55,845] After 0 (L:0 U:0 D:0) frames: @ 0.0 fps (avg@ 0.0 fps) (L:0.0 U:0.0 D:0.0) Stats:
{'loss_first': 0,
 'loss_landlord': 0,
 'loss_landlord_down': 0,
 'loss_landlord_up': 0,
 'loss_second': 0,
 'loss_third': 0,
 'mean_episode_return_first': 0,
 'mean_episode_return_landlord': 0,
 'mean_episode_return_landlord_down': 0,
 'mean_episode_return_landlord_up': 0,
 'mean_episode_return_second': 0,
 'mean_episode_return_third': 0}
[INFO:2890 dmc:259 2024-09-25 01:47:00,850] After 0 (L:0 U:0 D:0) frames: @ 0.0 fps (avg@ 0.0 fps) (L:0.0 U:0.0 D:0.0) Stats:
{'loss_first': 0,
 'loss_landlord': 0,
 'loss_landlord_down': 0,
 'loss_landlord_up': 0,
 'loss_second': 0,
 'loss_third': 0,
 'mean_episode_return_first': 0,
 'mean_episode_return_landlord': 0,
 'mean_episode_return_landlord_down': 0,
 'mean_episode_return_landlord_up': 0,
 'mean_episode_return_second': 0,
 'mean_episode_return_third': 0}
Learn landlord
Learn landlord_down
Learn landlord_up
Updated log fields: ['_tick', '_time', 'frames', 'mean_episode_return_first', 'loss_first', 'mean_episode_return_second', 'loss_second', 'mean_episode_return_third', 'loss_third', 'mean_episode_return_landlord', 'loss_landlord', 'mean_episode_return_landlord_up', 'loss_landlord_up', 'mean_episode_return_landlord_down', 'loss_landlord_down']
[INFO:2890 dmc:259 2024-09-25 01:47:05,856] After 9000 (L:3000 U:3000 D:3000) frames: @ 1798.2 fps (avg@ 599.4 fps) (L:599.4 U:599.4 D:599.4) Stats:
{'loss_first': 0,
 'loss_landlord': 1.0669366121292114,
 'loss_landlord_down': 1.0456690788269043,
 'loss_landlord_up': 1.0650025606155396,
 'loss_second': 0,
 'loss_third': 0,
 'mean_episode_return_first': 0,
 'mean_episode_return_landlord': -0.07843136787414551,
 'mean_episode_return_landlord_down': 0.07877128571271896,
 'mean_episode_return_landlord_up': 0.07910628616809845,
 'mean_episode_return_second': 0,
 'mean_episode_return_third': 0}
Learn landlord_down
```
It keeps getting stuck here, not finishing the run or printing.

**Comment by markc-614** [comment]
@EdwardPooh @Vincentzyx

**Comment by EvelynCarter** [comment]
期待大佬出现

**Comment by EdwardPooh** [comment]
This is because you set --total_frames=6000

This means that the program will stop outputting logs and stop batch training when the total training frames reaches 6000, but will not terminate the batch generation process. So the program doesn't seem to output but doesn't terminate either.

**Comment by markc-614** [comment]
@EdwardPooh Is there any way to set it to run only a fixed number of iterations? I want to profiler the performance. Thanks

**Comment by EdwardPooh** [comment]
- The program saves by time, e.g. every 10 minutes (--save_interval 10), and each time it saves it outputs 6 .ckpt weight files for checkpoint testing.

- If you want to save by total number of frames, you need to modify the save logic by changing the time-based judgment in the dmc.py file (line 246) to whether the current number of frames minus the number of frames at the last save is greater than or equal to the desired frame interval.

- Note that saving takes time, training and saving are parallel, and even with the above improvements, you may not be able to save at the frame rate you want, e.g., if you want an interval of 100000 frames, and the number of frames at the last save was 0, then the saved model may be 100600.

**Comment by Vincentzyx** [comment]
> @EdwardPooh Is there any way to set it to run only a fixed number of iterations? I want to profiler the performance. Thanks

You can just setup a counter in dmc/utils.py, let the actor loop to quit after x games that you would like. That's how I do the profiling.

**Comment by markc-614** [comment]
@Vincentzyx 
Modify it as follows, but it still gets stuck
```
diff --git a/Douzero_Resnet/douzero/dmc/utils.py b/Douzero_Resnet/douzero/dmc/utils.py
index f70431d..905ba83 100644
--- a/Douzero_Resnet/douzero/dmc/utils.py
+++ b/Douzero_Resnet/douzero/dmc/utils.py
@@ -61,6 +61,7 @@ def create_optimizers(flags, learner_model):
     return optimizers
 
 
+act_counter = 0
 def act(i, device, batch_queues, model, flags):
     positions = ['first', 'second', 'third', 'landlord', 'landlord_up', 'landlord_down']
     try:
@@ -81,7 +82,11 @@ def act(i, device, batch_queues, model, flags):
 
         position, obs, env_output = env.initial(model, device, flags=flags)
 
+        global act_counter
         while True:
+            act_counter = act_counter + 1
+            if act_counter > 10:
+                return
             while True:
 
                 if len(obs['legal_actions']) > 1:
```
run cmd
```
python train.py
```

**Comment by EdwardPooh** [comment]
> @Vincentzyx Modify it as follows, but it still gets stuck
> 
> ```
> diff --git a/Douzero_Resnet/douzero/dmc/utils.py b/Douzero_Resnet/douzero/dmc/utils.py
> index f70431d..905ba83 100644
> --- a/Douzero_Resnet/douzero/dmc/utils.py
> +++ b/Douzero_Resnet/douzero/dmc/utils.py
> @@ -61,6 +61,7 @@ def create_optimizers(flags, learner_model):
>      return optimizers
>  
>  
> +act_counter = 0
>  def act(i, device, batch_queues, model, flags):
>      positions = ['first', 'second', 'third', 'landlord', 'landlord_up', 'landlord_down']
>      try:
> @@ -81,7 +82,11 @@ def act(i, device, batch_queues, model, flags):
>  
>          position, obs, env_output = env.initial(model, device, flags=flags)
>  
> +        global act_counter
>          while True:
> +            act_counter = act_counter + 1
> +            if act_counter > 10:
> +                return
>              while True:
>  
>                  if len(obs['legal_actions']) > 1:
> ```
> 
> run cmd
> 
> ```
> python train.py
> ```

Return aborts the act function so that data cannot be generated and training cannot continue, but the checkpoints is updated.
