### ISSUE TITLE
关于训练效率的问题 Problem regarding training efficiency

### ISSUE THREAD

**Issue by FYNIXqwq** [EdwardPooh/douzero-resnet-2.0#2]
![image](https://user-images.githubusercontent.com/51454565/236806569-0b27e1d6-cad0-4260-bbb1-b4b6fa32aeb1.png)
使用相同配置的云算力平台（5*RTX3070），训练普通DouZero时帧率可达4500到5000FPS。但是训练本项目时5张RTX3070只能发挥出2000FPS的训练速度（超参数按照默认设置）。考虑到训练过程还包含了叫牌，这是否意味着这个模型训练到相同的效果（例如胜率、ADP）只需要用比传统DouZero模型少得多的帧数就足够了呢？

**Comment by EdwardPooh** [comment]
训练速度慢是因为模型较大并且卷积计算速度较慢，可以尝试换用具有高并行效率的transformer架构来保证模型大小的情况下提升训练速度。
