### ISSUE TITLE
关于不洗牌模式的训练 Questions about training under "Shuffleless" method

### ISSUE THREAD

**Issue by FYNIXqwq** [EdwardPooh/douzero-resnet-2.0#3]
不洗牌模式的一大特点是牌型整齐和bomb_count高，但偶尔会出现几张散牌。目前我已经通过先随机排列点数，再按照点数生成牌堆，并对牌堆进行随机位置、随机次数的切牌达到类似于不洗牌模式的效果。但是在训练传统DouZero时出现了很多问题。
1. 在胜率为目标的训练中，很容易出现激进的出牌方式（如作为农民时很少给队友留机会，作为地主时很少考虑散牌如何尽快出干净），而在以ADT为目标的训练中，由于AI已经认识到bomb_count增加会导致ADT的结果翻倍，而每一局的平均bomb_count可以达到7左右，因此在实际的游戏操作中，即使是玩家几乎必赢的“天牌”（如DX2222AAAKTTTT666633），AI由于认识到输赢之间奖惩的悬殊（高则数百，低则负数百），所以它依然会采取拆牌的策略，大幅减少可能的bomb_count，例如在一次联机对战中，AI认为6666DX四带二比先出33对子具有更高的ADT。这个项目的参数比传统DouZero更多，确实对训练不洗牌有帮助，但是我仍然希望能看到关于这个项目训练不洗牌有价值的建议，谢谢。
//这个问题还导致异常高的loss，在训练不洗牌时如果把炸弹翻倍调整至默认的2.0，loss可以达到数万甚至数十万，只有将炸弹翻倍先降低到约1.2x时，loss才可能随着帧数增长到100M左右时稳定降低到1以内，但降低炸弹翻倍的底数则意味着在赢面很大的场合，AI并不能有效采取激进策略。
2. 在传统douzero中，env.py是唯一存在生成牌堆、发牌的代码且能影响到训练的文件，而在这个项目中，游戏模拟的过程变得复杂了。例如，一轮游戏中，如果三名玩家都不叫地主，则重新生成牌堆并重新发牌。但由于文件结构更加复杂，我想询问这个项目里env.py是否为唯一存在生成牌堆、发牌的代码且能影响到训练的文件，以及当三人都不叫地主后重新生成牌堆、发牌是否为直接调用env.py的牌堆生成过程。
3. 关于此项目与DouZero_For_HLDDZ_Full_Auto的联系。DouZero_For_HLDDZ_Full_Auto里面有几个pkl文件影响着软件判断叫地主或者不叫地主的胜率，以及接下来怎么出牌胜算更高。然而很显然这些pkl文件是基于洗牌模式训练、生成的。我在DouZero_For_HLDDZ_Full_Auto只找到了如何调用它们的代码以及readme.md当中对自动j叫牌和加倍的原理的简单介绍，并不知道它们时如何生成的。显然对于不洗牌模式，虽然出牌方式是一样的，但是游戏策略和传统模式是有很大不同的。所以希望在不久的将来能够看到这些pkl是如何生成的。

**Comment by EdwardPooh** [comment]
训练过程中发牌只会在env.py中进行。如果你想训练不洗牌模式，你可以尝试给模型获得的奖励加上封顶，同时可以将sigmoid应用于模型输出进行归一化保证收敛。

DouZero_For_HLDDZ_Full_Auto与本项目无关，项目中的pkl是通过固定17张手牌并随机产生地主牌和农民手牌来产生100组对局并用evaluate.py进行评估得分产生训练集监督学习得到的，是对叫牌的一种简单代替。

**Comment by FYNIXqwq** [comment]
![image](https://user-images.githubusercontent.com/51454565/236834006-df62a301-69c8-40b7-a0b3-b77631209668.png)
将代码（此项目中的env.py）改成这样是不是就能保证每一次发牌（包括三家都没有叫地主而重新发牌）都是按照不洗牌生成牌堆？（deck_generate()是我写的生成不洗牌模式54张牌堆的函数）

**Comment by FYNIXqwq** [comment]
![image](https://user-images.githubusercontent.com/51454565/236834006-df62a301-69c8-40b7-a0b3-b77631209668.png)
将代码（此项目中的env.py）改成这样是不是就能保证每一次发牌（包括三家都没有叫地主而重新发牌）都是按照不洗牌生成牌堆？（deck_generate()是我写的生成不洗牌模式54张牌堆的函数）

**Comment by FYNIXqwq** [comment]
另外env.py是不是唯一可以修改训练奖惩机制的文件？

**Comment by EdwardPooh** [comment]
你写的发牌看起来是对的，你可以在env.py中设置阶段奖励。神经网络的学习是通过“输出”和“目标”计算一个损失函数并梯度下降进行的，在你的“阶段奖励”成为你进行训练的“目标”并计算损失函数之前的任意一个阶段你都可以修改它，这可能会涉及到很多个文件。

**Comment by FYNIXqwq** [comment]
env中的self._env.step_count是不是指的玩家从开始到结束出牌的次数？

**Comment by FYNIXqwq** [comment]
env中的self._env.step_count是不是指的玩家从开始到结束出牌的次数？因为我看奖励和这个参数负相关。
