### ISSUE TITLE
2.0版的效果如问

### ISSUE THREAD

**Issue by lbyczzz** [EdwardPooh/douzero-resnet-2.0#4]
请问下你这个版本的网络训练出来的模型效果如何啊，有没有做过对比啊

**Comment by EdwardPooh** [comment]
你可以尝试克隆该项目并训练权重进行测试。运行evaluate.py你可以选择测试douzero或者douzero_resnet，测试权重分别在baseline/test和best文件夹。

**Comment by lbyczzz** [comment]
好的，谢谢。那个test文件下的是原douzero作者提供的模型吗，是基于ADP还是WP的？

**Comment by EdwardPooh** [comment]
是基于ADP奖励的权重

**Comment by lbyczzz** [comment]
好的  谢谢。
